// frontend/src/pages/ImportPage.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { AlertCircle, CheckCircle2, FileUp, LoaderCircle, Trash2 } from "lucide-vue-next";

import { ApiError } from "@/api/client";
import { importFiles, type ImportTaskResponse } from "@/api/knowledge";
import PageHeader from "@/components/shared/PageHeader.vue";
import { formatBytes } from "@/lib/utils";

const allowedExt = ["pdf", "md", "docx", "txt"];
const singleLimit = 20 * 1024 * 1024;
const batchLimit = 200 * 1024 * 1024;

interface PickedFile {
  file: File;
  error?: string;
}

const fileInput = ref<HTMLInputElement | null>(null);
const picked = ref<PickedFile[]>([]);
const dragging = ref(false);
const uploading = ref(false);
const result = ref<ImportTaskResponse | null>(null);
const error = ref<string | null>(null);

const validFiles = computed(() => picked.value.filter((item) => !item.error).map((item) => item.file));
const hasInvalid = computed(() => picked.value.some((item) => item.error));
const totalSize = computed(() => picked.value.reduce((sum, item) => sum + item.file.size, 0));

function extOf(name: string): string {
  return name.split(".").pop()?.toLowerCase() ?? "";
}

function validate(file: File): PickedFile {
  const ext = extOf(file.name);
  if (!allowedExt.includes(ext)) {
    return { file, error: `不支持的格式 .${ext}（仅 PDF / MD / DOCX / TXT）` };
  }
  if (file.size > singleLimit) {
    return { file, error: `超过单文件 20MB 限制（${formatBytes(file.size)}）` };
  }
  return { file };
}

function addFiles(files: File[]) {
  result.value = null;
  error.value = null;
  const incoming = files.map(validate);
  const next = [...picked.value, ...incoming];
  const bytes = next.reduce((sum, item) => sum + item.file.size, 0);
  if (bytes > batchLimit) {
    error.value = `批量总大小超过 200MB（当前 ${formatBytes(bytes)}），请分批上传`;
    return;
  }
  picked.value = next;
}

function onFileChange(event: Event) {
  const input = event.target as HTMLInputElement;
  addFiles(Array.from(input.files ?? []));
  input.value = "";
}

function onDrop(event: DragEvent) {
  dragging.value = false;
  addFiles(Array.from(event.dataTransfer?.files ?? []));
}

async function upload() {
  if (!validFiles.value.length || hasInvalid.value) return;
  uploading.value = true;
  error.value = null;
  result.value = null;
  try {
    result.value = await importFiles(validFiles.value);
    picked.value = [];
  } catch (err) {
    if (err instanceof ApiError) {
      const reasonMap: Record<string, string> = {
        content_duplicate: "存在重复内容（SHA-256 哈希命中），请检查文件",
        file_too_large: "文件超过大小限制",
        unsupported_media_type: "存在不支持的文件格式",
      };
      error.value = reasonMap[err.errorCode ?? ""] ?? err.message;
    } else {
      error.value = "上传失败，请重试";
    }
  } finally {
    uploading.value = false;
  }
}
</script>

<template>
  <div class="animate-fade-up">
    <PageHeader
      title="产品文档导入"
      description="PDF/DOCX 优先走 MinerU 结构化解析；失败时按配置回退原生解析器，再按章节/页码切片并写入 Milvus。"
    >
      <template #actions>
        <button
          class="flex h-10 items-center gap-2 rounded-md bg-brand px-4 text-sm font-bold text-navy-deep disabled:opacity-50"
          :disabled="uploading || validFiles.length === 0 || hasInvalid"
          @click="upload"
        >
          <LoaderCircle v-if="uploading" class="h-4 w-4 animate-spin" aria-hidden="true" />
          <FileUp v-else class="h-4 w-4" aria-hidden="true" />
          {{ uploading ? "上传中…" : `开始导入（${validFiles.length}）` }}
        </button>
      </template>
    </PageHeader>

    <section
      class="rounded-xl border-2 border-dashed bg-card p-8 text-center transition"
      :class="dragging ? 'border-brand bg-brand-soft/50' : 'border-boundary'"
      @dragenter.prevent="dragging = true"
      @dragover.prevent="dragging = true"
      @dragleave.prevent="dragging = false"
      @drop.prevent="onDrop"
    >
      <FileUp class="mx-auto h-10 w-10 text-brand" aria-hidden="true" />
      <p class="mt-3 font-display font-bold text-ink">拖拽产品文档到此处</p>
      <p class="mt-1 text-sm text-secondarytext">支持 PDF / DOCX / Markdown / TXT；单文件 ≤ 20MB，批次 ≤ 200MB</p>
      <button
        class="mt-4 rounded-md border border-boundary bg-white px-4 py-2 text-sm font-medium text-ink hover:bg-mist"
        @click="fileInput?.click()"
      >
        选择文件
      </button>
      <input
        ref="fileInput"
        type="file"
        multiple
        accept=".pdf,.docx,.md,.txt"
        class="hidden"
        @change="onFileChange"
      />
    </section>

    <div v-if="error" class="mt-4 flex items-center gap-2 rounded-lg border border-danger/30 bg-danger-soft p-4 text-sm text-danger">
      <AlertCircle class="h-4 w-4" aria-hidden="true" />{{ error }}
    </div>

    <section v-if="picked.length" class="mt-5 overflow-hidden rounded-xl border border-boundary bg-card">
      <header class="flex items-center justify-between border-b border-boundary px-5 py-3">
        <p class="font-display font-bold text-ink">待导入文件</p>
        <span class="code-text text-secondarytext">{{ picked.length }} 个 · {{ formatBytes(totalSize) }}</span>
      </header>
      <ul class="divide-y divide-boundary">
        <li v-for="(item, index) in picked" :key="`${item.file.name}-${index}`" class="flex items-center gap-3 px-5 py-3">
          <div class="min-w-0 flex-1">
            <p class="truncate text-sm font-medium text-ink">{{ item.file.name }}</p>
            <p class="code-text mt-0.5 text-secondarytext">{{ formatBytes(item.file.size) }}</p>
            <p v-if="item.error" class="mt-1 text-xs text-danger">{{ item.error }}</p>
          </div>
          <button class="rounded-md p-2 text-secondarytext hover:bg-danger-soft hover:text-danger" @click="picked.splice(index, 1)">
            <Trash2 class="h-4 w-4" aria-hidden="true" />
          </button>
        </li>
      </ul>
    </section>

    <section v-if="result" class="mt-5 rounded-xl border border-brand/40 bg-brand-soft p-5">
      <p class="flex items-center gap-2 font-display font-bold text-ink">
        <CheckCircle2 class="h-5 w-5 text-brand" aria-hidden="true" />
        导入任务已创建
      </p>
      <p class="code-text mt-2 text-secondarytext">task_id: {{ result.task_id }}</p>
      <p class="mt-2 text-sm text-primarytext">
        接受 {{ result.accepted_count ?? result.accepted ?? 0 }} 个文件，
        拒绝 {{ result.rejected.length }} 个文件。
      </p>
      <ul v-if="result.rejected.length" class="mt-3 space-y-1 text-xs text-danger">
        <li v-for="item in result.rejected" :key="item.filename">{{ item.filename }}：{{ item.reason }}</li>
      </ul>
    </section>
  </div>
</template>

// frontend/src/pages/ImportPage.tsx
import { useRef, useState } from "react";
import { FileUp, CheckCircle2, AlertCircle, Loader2 } from "lucide-react";
import { PageHeader } from "@/components/shared/PageHeader";
import { Button } from "@/components/ui/button";
import { importFiles, type ImportTaskResponse } from "@/api/knowledge";
import { ApiError } from "@/api/client";
import { formatBytes, cn } from "@/lib/utils";

const ALLOWED_EXT = ["pdf", "md", "docx", "txt"];
const SINGLE_LIMIT = 20 * 1024 * 1024; // 单文件 20MB
const BATCH_LIMIT = 200 * 1024 * 1024; // 批量 200MB

interface PickedFile {
  file: File;
  error?: string; // 客户端预校验（类型/大小）
}

function extOf(name: string): string {
  return name.split(".").pop()?.toLowerCase() ?? "";
}

export default function ImportPage() {
  const inputRef = useRef<HTMLInputElement>(null);
  const [files, setFiles] = useState<PickedFile[]>([]);
  const [dragging, setDragging] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [result, setResult] = useState<ImportTaskResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  const validate = (incoming: File[]): PickedFile[] => {
    return incoming.map((file) => {
      const ext = extOf(file.name);
      if (!ALLOWED_EXT.includes(ext)) {
        return { file, error: `不支持的格式 .${ext}（仅 PDF / MD / DOCX / TXT）` };
      }
      if (file.size > SINGLE_LIMIT) {
        return { file, error: `超过单文件 20MB 限制（${formatBytes(file.size)}）` };
      }
      return { file };
    });
  };

  const addFiles = (incoming: File[]) => {
    setResult(null);
    setError(null);
    setFiles((prev) => {
      const merged = [...prev, ...validate(incoming)];
      // 客户端提前拦截批量总大小 200MB
      const total = merged.reduce((s, f) => s + f.file.size, 0);
      if (total > BATCH_LIMIT) {
        setError(`批量总大小超过 200MB（当前 ${formatBytes(total)}），请分批上传`);
        return prev;
      }
      return merged;
    });
  };

  const validFiles = files.filter((f) => !f.error).map((f) => f.file);
  const hasInvalid = files.some((f) => f.error);

  const handleUpload = async () => {
    if (validFiles.length === 0) return;
    setUploading(true);
    setError(null);
    setResult(null);
    try {
      const resp = await importFiles(validFiles);
      setResult(resp);
      setFiles([]);
    } catch (err) {
      // 409 content_duplicate / 413 file_too_large / 415 unsupported_media_type
      if (err instanceof ApiError) {
        const reasonMap: Record<string, string> = {
          content_duplicate: "存在重复内容（SHA-256 哈希命中），请检查文件",
          file_too_large: "文件超过大小限制",
          unsupported_media_type: "存在不支持的文件格式",
        };
        setError(`${reasonMap[err.errorCode ?? ""] ?? err.message}`);
      } else {
        setError("上传失败，请重试");
      }
    } finally {
      setUploading(false);
    }
  };

  return (
    <div className="animate-fade-up">
      <PageHeader
        title="知识导入中心"
        description="上传 PDF / Markdown / DOCX / TXT 文档，服务端解析切片后向量化入库。"
        actions={
          <Button onClick={() => void handleUpload()} disabled={uploading || validFiles.length === 0 || hasInvalid}>
            {uploading ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" aria-hidden /> 上传中…
              </>
            ) : (
              <>
                <FileUp className="h-4 w-4" aria-hidden /> 上传 {validFiles.length > 0 ? `（${validFiles.length} 个文件）` : ""}
              </>
            )}
          </Button>
        }
      />

      {/* 拖拽区 */}
      <div
        role="button"
        tabIndex={0}
        aria-label="拖拽或选择文件上传"
        onClick={() => inputRef.current?.click()}
        onKeyDown={(e) => e.key === "Enter" && inputRef.current?.click()}
        onDragOver={(e) => {
          e.preventDefault();
          setDragging(true);
        }}
        onDragLeave={() => setDragging(false)}
        onDrop={(e) => {
          e.preventDefault();
          setDragging(false);
          addFiles(Array.from(e.dataTransfer.files));
        }}
        className={cn(
          "flex min-h-[200px] cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed px-6 py-10 text-center transition",
          dragging ? "border-brand bg-brand-soft" : "border-boundary bg-card/60 hover:border-brand/60",
        )}
      >
        <div className="flex h-14 w-14 items-center justify-center rounded-full bg-mist">
          <FileUp className="h-6 w-6 text-brand" aria-hidden />
        </div>
        <p className="mt-4 font-display text-base font-bold text-ink">拖拽文件到此处，或点击选择</p>
        <p className="mt-1.5 text-sm text-secondarytext">
          支持 PDF / MD / DOCX / TXT · 单文件 ≤ 20MB · 批量 ≤ 200MB
        </p>
        <input
          ref={inputRef}
          type="file"
          multiple
          accept=".pdf,.md,.docx,.txt"
          className="hidden"
          onChange={(e) => {
            addFiles(Array.from(e.target.files ?? []));
            e.target.value = "";
          }}
        />
      </div>

      {error && (
        <p role="alert" className="mt-4 flex items-center gap-2 rounded-md bg-danger-soft px-4 py-3 text-sm text-danger">
          <AlertCircle className="h-4 w-4 shrink-0" aria-hidden /> {error}
        </p>
      )}

      {/* 待上传文件列表：文件级状态 */}
      {files.length > 0 && (
        <ul className="mt-4 divide-y divide-boundary rounded-lg border border-boundary bg-card">
          {files.map((f, i) => (
            <li key={`${f.file.name}-${i}`} className="flex items-center gap-3 px-4 py-3">
              {f.error ? (
                <AlertCircle className="h-4 w-4 shrink-0 text-danger" aria-hidden />
              ) : (
                <CheckCircle2 className="h-4 w-4 shrink-0 text-brand" aria-hidden />
              )}
              <span className="code-text min-w-0 flex-1 truncate text-[13px] text-primarytext">
                {f.file.name}
              </span>
              <span className="shrink-0 text-xs text-secondarytext">{formatBytes(f.file.size)}</span>
              {f.error && <span className="shrink-0 text-xs text-danger">{f.error}</span>}
              <button
                aria-label={`移除 ${f.file.name}`}
                onClick={() => setFiles((prev) => prev.filter((_, idx) => idx !== i))}
                className="h-11 shrink-0 px-2 text-sm text-secondarytext hover:text-danger"
              >
                移除
              </button>
            </li>
          ))}
        </ul>
      )}

      {/* 导入结果 */}
      {result && (
        <div className="mt-4 rounded-lg border border-brand/40 bg-brand-soft px-4 py-4">
          <p className="flex items-center gap-2 font-medium text-ink">
            <CheckCircle2 className="h-4 w-4 text-brand" aria-hidden />
            已受理 {result.accepted_count ?? result.accepted ?? validFiles.length} 个文件（任务 {result.task_id}），解析与向量化进行中
          </p>
          {result.rejected?.length > 0 && (
            <ul className="mt-2 space-y-1">
              {result.rejected.map((r) => (
                <li key={r.filename} className="text-[13px] text-secondarytext">
                  {r.filename}：{r.reason}
                </li>
              ))}
            </ul>
          )}
          <p className="mt-2 text-xs text-secondarytext">
            可前往「知识单元」查看解析与向量化状态（active / vector_pending / failed）。
          </p>
        </div>
      )}
    </div>
  );
}
