// frontend/src/pages/KnowledgeUnitsPage.vue
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import {
  AlertCircle,
  CheckCircle2,
  DatabaseZap,
  FileSearch,
  LoaderCircle,
  RefreshCw,
  Save,
  Search,
  Trash2,
  X,
} from "lucide-vue-next";

import { ApiError } from "@/api/client";
import {
  batchDeleteUnits,
  getKnowledgeIndexStatus,
  getKnowledgeUnit,
  getKnowledgeUnits,
  patchKnowledgeUnit,
  reindexKnowledgeUnit,
  type KnowledgeIndexStatus,
  type KnowledgeUnitDetail,
  type KnowledgeUnitItem,
  type PermissionEntry,
} from "@/api/knowledge";
import KnowledgePermissionEditor from "@/components/knowledge/KnowledgePermissionEditor.vue";
import PageHeader from "@/components/shared/PageHeader.vue";
import { formatDateTime } from "@/lib/utils";
import { useAuthStore } from "@/stores/auth";

const auth = useAuthStore();

const rows = ref<KnowledgeUnitItem[]>([]);
const total = ref(0);
const page = ref(1);
const pageSize = 20;
const keyword = ref("");
const status = ref("");
const loading = ref(false);
const error = ref<string | null>(null);

const detail = ref<KnowledgeUnitDetail | null>(null);
const detailLoading = ref(false);
const saving = ref(false);
const deleting = ref(false);
const reindexing = ref(false);
const indexStatus = ref<KnowledgeIndexStatus | null>(null);
const panelError = ref<string | null>(null);

const edit = reactive({ title: "", category: "", summary: "", content: "" });
const pages = computed(() => Math.max(1, Math.ceil(total.value / pageSize)));

async function load() {
  loading.value = true;
  error.value = null;
  try {
    const response = await getKnowledgeUnits({
      page: page.value,
      page_size: pageSize,
      keyword: keyword.value || undefined,
      status: status.value || undefined,
    });
    rows.value = response.items;
    total.value = response.total;
  } catch (err) {
    error.value = err instanceof ApiError ? err.message : "知识资产加载失败";
  } finally {
    loading.value = false;
  }
}

async function openDetail(id: number) {
  detailLoading.value = true;
  panelError.value = null;
  indexStatus.value = null;
  try {
    const [unit, health] = await Promise.all([
      getKnowledgeUnit(id),
      getKnowledgeIndexStatus(id).catch(() => null),
    ]);
    detail.value = unit;
    indexStatus.value = health;
    edit.title = unit.title;
    edit.category = unit.category ?? "";
    edit.summary = unit.summary ?? "";
    edit.content = unit.content;
  } catch (err) {
    panelError.value = err instanceof ApiError ? err.message : "知识详情加载失败";
  } finally {
    detailLoading.value = false;
  }
}

async function save() {
  if (!detail.value) return;
  saving.value = true;
  panelError.value = null;
  try {
    const updated = await patchKnowledgeUnit(detail.value.id, {
      title: edit.title.trim(),
      category: edit.category.trim(),
      summary: edit.summary.trim(),
      content: edit.content,
    });
    detail.value = await getKnowledgeUnit(updated.id);
    edit.title = detail.value.title;
    edit.category = detail.value.category ?? "";
    edit.summary = detail.value.summary ?? "";
    edit.content = detail.value.content;
    indexStatus.value = await getKnowledgeIndexStatus(updated.id).catch(() => null);
    await load();
  } catch (err) {
    panelError.value =
      err instanceof ApiError
        ? `${err.message}${err.errorCode === "knowledge_index_sync_failed" ? "（正文已保存为 vector_pending，可稍后重建索引）" : ""}`
        : "保存失败";
    if (detail.value) {
      indexStatus.value = await getKnowledgeIndexStatus(detail.value.id).catch(() => null);
    }
  } finally {
    saving.value = false;
  }
}

async function reindex() {
  if (!detail.value) return;
  reindexing.value = true;
  panelError.value = null;
  try {
    indexStatus.value = await reindexKnowledgeUnit(detail.value.id);
    detail.value = await getKnowledgeUnit(detail.value.id);
    await load();
  } catch (err) {
    panelError.value = err instanceof ApiError ? err.message : "索引重建失败";
  } finally {
    reindexing.value = false;
  }
}

async function remove() {
  if (!detail.value || !window.confirm(`确认删除知识单元「${detail.value.title}」？`)) return;
  deleting.value = true;
  try {
    await batchDeleteUnits([detail.value.id]);
    detail.value = null;
    indexStatus.value = null;
    await load();
  } catch (err) {
    panelError.value = err instanceof ApiError ? err.message : "删除失败";
  } finally {
    deleting.value = false;
  }
}

async function handlePermissionsSaved(permissions: PermissionEntry[]) {
  if (!detail.value) return;
  detail.value = {
    ...detail.value,
    permissions,
    permissions_summary:
      permissions.length === 1 && permissions[0]?.target_type === "global"
        ? "全局公开"
        : permissions
            .slice(0, 3)
            .map((item) => item.target_label || item.target_type)
            .join(" + ") + (permissions.length > 3 ? "…" : ""),
  };
  panelError.value = null;
  await load();
}

function submitSearch() {
  page.value = 1;
  void load();
}

function statusLabel(value: KnowledgeUnitItem["status"]): string {
  if (value === "active") return "可检索";
  if (value === "vector_pending") return "待向量化";
  return "失败";
}

onMounted(() => void load());
</script>

<template>
  <div class="animate-fade-up">
    <PageHeader
      title="知识资产"
      description="管理 ERP/WMS 产品知识正文、版本状态、来源文件、权限摘要与 Milvus chunk 索引健康。"
    />

    <section class="mb-4 flex flex-col gap-3 rounded-xl border border-boundary bg-card p-4 sm:flex-row">
      <form class="flex min-w-0 flex-1 gap-2" @submit.prevent="submitSearch">
        <div class="relative min-w-0 flex-1">
          <Search class="absolute left-3 top-3 h-4 w-4 text-secondarytext" aria-hidden="true" />
          <input
            v-model.trim="keyword"
            class="h-10 w-full rounded-md border border-boundary bg-white pl-9 pr-3 text-sm"
            placeholder="按标题、内容或来源搜索"
          />
        </div>
        <button class="rounded-md bg-ink px-4 text-sm font-medium text-white">搜索</button>
      </form>
      <select v-model="status" class="h-10 rounded-md border border-boundary bg-white px-3 text-sm" @change="submitSearch">
        <option value="">全部状态</option>
        <option value="active">active</option>
        <option value="vector_pending">vector_pending</option>
        <option value="failed">failed</option>
      </select>
    </section>

    <div v-if="error" class="mb-4 rounded-lg border border-danger/30 bg-danger-soft p-4 text-sm text-danger">{{ error }}</div>

    <section class="overflow-hidden rounded-xl border border-boundary bg-card">
      <div v-if="loading" class="flex min-h-64 items-center justify-center text-secondarytext">
        <LoaderCircle class="mr-2 h-5 w-5 animate-spin" />加载中…
      </div>
      <div v-else-if="!rows.length" class="py-16 text-center text-sm text-secondarytext">暂无知识资产</div>
      <div v-else class="overflow-x-auto">
        <table class="w-full min-w-[900px] text-left text-sm">
          <thead class="bg-mist text-xs text-secondarytext">
            <tr>
              <th class="px-4 py-3 font-medium">知识单元</th>
              <th class="px-4 py-3 font-medium">业务分类</th>
              <th class="px-4 py-3 font-medium">状态</th>
              <th class="px-4 py-3 font-medium">权限</th>
              <th class="px-4 py-3 font-medium">来源</th>
              <th class="px-4 py-3 font-medium">更新时间</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-boundary">
            <tr v-for="row in rows" :key="row.id" class="cursor-pointer hover:bg-mist/70" @click="openDetail(row.id)">
              <td class="px-4 py-3">
                <p class="font-medium text-ink">{{ row.title }}</p>
                <p class="code-text mt-0.5 text-secondarytext">{{ row.unit_code }}</p>
              </td>
              <td class="px-4 py-3 text-secondarytext">{{ row.category ?? "—" }}</td>
              <td class="px-4 py-3">
                <span
                  class="rounded-full px-2.5 py-1 text-xs font-semibold"
                  :class="row.status === 'active' ? 'bg-brand-soft text-ink' : 'bg-review-soft text-review'"
                >
                  {{ statusLabel(row.status) }}
                </span>
              </td>
              <td class="px-4 py-3 text-secondarytext">{{ row.permissions_summary || "未配置" }}</td>
              <td class="max-w-48 truncate px-4 py-3 text-secondarytext" :title="row.source_file_name ?? ''">
                {{ row.source_file_name ?? row.file_type ?? "手工知识" }}
              </td>
              <td class="px-4 py-3 text-xs text-secondarytext">{{ formatDateTime(row.updated_at) }}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <footer class="flex items-center justify-between border-t border-boundary px-4 py-3 text-sm text-secondarytext">
        <span>共 {{ total }} 条</span>
        <div class="flex items-center gap-2">
          <button class="rounded border border-boundary px-3 py-1.5 disabled:opacity-40" :disabled="page <= 1" @click="page--; load()">上一页</button>
          <span class="code-text">{{ page }} / {{ pages }}</span>
          <button class="rounded border border-boundary px-3 py-1.5 disabled:opacity-40" :disabled="page >= pages" @click="page++; load()">下一页</button>
        </div>
      </footer>
    </section>

    <div v-if="detail || detailLoading" class="fixed inset-0 z-50 flex justify-end bg-navy-deep/35" @click.self="detail = null">
      <aside class="h-full w-full max-w-2xl overflow-y-auto bg-mist p-5 shadow-2xl">
        <div class="flex items-center justify-between">
          <h2 class="font-display text-xl font-extrabold text-ink">知识单元详情</h2>
          <button class="rounded-md p-2 text-secondarytext hover:bg-boundary/50" @click="detail = null">
            <X class="h-5 w-5" />
          </button>
        </div>

        <div v-if="detailLoading" class="flex min-h-60 items-center justify-center text-secondarytext">
          <LoaderCircle class="mr-2 h-5 w-5 animate-spin" />加载详情…
        </div>

        <template v-else-if="detail">
          <div
            v-if="indexStatus"
            class="mt-5 rounded-xl border p-4"
            :class="indexStatus.consistent ? 'border-brand/40 bg-brand-soft' : 'border-review/50 bg-review-soft'"
          >
            <div class="flex items-start justify-between gap-3">
              <div>
                <p class="flex items-center gap-2 font-display font-bold text-ink">
                  <CheckCircle2 v-if="indexStatus.consistent" class="h-4 w-4 text-brand" />
                  <AlertCircle v-else class="h-4 w-4 text-review" />
                  向量索引：{{ indexStatus.consistent ? "一致" : "需要处理" }}
                </p>
                <p class="code-text mt-1 text-secondarytext">
                  DB={{ indexStatus.db_status }} · chunks={{ indexStatus.chunk_count ?? "未启用" }} · {{ indexStatus.detail }}
                </p>
              </div>
              <button
                v-if="auth.can('knowledge:write')"
                class="flex items-center gap-1 rounded-md border border-boundary bg-white px-3 py-2 text-xs font-medium text-ink"
                :disabled="reindexing"
                @click="reindex"
              >
                <RefreshCw class="h-3.5 w-3.5" :class="{ 'animate-spin': reindexing }" />
                {{ reindexing ? "重建中" : "重建索引" }}
              </button>
            </div>
          </div>

          <div v-if="panelError" class="mt-4 rounded-lg border border-danger/30 bg-danger-soft p-3 text-sm text-danger">
            {{ panelError }}
          </div>

          <div class="mt-5 space-y-4">
            <label class="block">
              <span class="text-xs font-medium text-secondarytext">标题</span>
              <input v-model="edit.title" class="mt-1 h-10 w-full rounded-md border border-boundary bg-white px-3 text-sm" :disabled="!auth.can('knowledge:write')" />
            </label>
            <div class="grid gap-4 sm:grid-cols-2">
              <label>
                <span class="text-xs font-medium text-secondarytext">分类</span>
                <input v-model="edit.category" class="mt-1 h-10 w-full rounded-md border border-boundary bg-white px-3 text-sm" :disabled="!auth.can('knowledge:write')" />
              </label>
              <div>
                <span class="text-xs font-medium text-secondarytext">来源文件</span>
                <p class="code-text mt-2 text-ink">{{ detail.source_file_name ?? "手工知识" }}</p>
              </div>
            </div>
            <label class="block">
              <span class="text-xs font-medium text-secondarytext">摘要</span>
              <textarea v-model="edit.summary" rows="3" class="mt-1 w-full rounded-md border border-boundary bg-white p-3 text-sm" :disabled="!auth.can('knowledge:write')" />
            </label>
            <label class="block">
              <span class="text-xs font-medium text-secondarytext">正文</span>
              <textarea v-model="edit.content" rows="14" class="code-text mt-1 w-full rounded-md border border-boundary bg-white p-3 leading-6" :disabled="!auth.can('knowledge:write')" />
            </label>

            <div>
              <p class="text-xs font-medium text-secondarytext">当前权限范围</p>
              <div class="mt-2 flex flex-wrap gap-2">
                <span
                  v-for="permission in detail.permissions"
                  :key="`${permission.target_type}-${permission.target_id}`"
                  class="rounded-full bg-white px-3 py-1 text-xs text-ink ring-1 ring-boundary"
                >
                  {{ permission.target_type }} · {{ permission.target_label }}
                </span>
                <span v-if="!detail.permissions.length" class="text-xs text-secondarytext">未配置</span>
              </div>
            </div>

            <KnowledgePermissionEditor
              v-if="auth.can('knowledge:assign_permission')"
              :unit-id="detail.id"
              :permissions="detail.permissions"
              @saved="handlePermissionsSaved"
            />
          </div>

          <div class="mt-6 flex flex-wrap justify-end gap-2 border-t border-boundary pt-4">
            <button
              v-if="auth.can('knowledge:delete')"
              class="flex items-center gap-2 rounded-md border border-danger/30 bg-danger-soft px-4 py-2 text-sm font-medium text-danger"
              :disabled="deleting"
              @click="remove"
            >
              <Trash2 class="h-4 w-4" />{{ deleting ? "删除中…" : "删除" }}
            </button>
            <button
              v-if="auth.can('knowledge:write')"
              class="flex items-center gap-2 rounded-md bg-brand px-4 py-2 text-sm font-bold text-navy-deep disabled:opacity-50"
              :disabled="saving"
              @click="save"
            >
              <Save class="h-4 w-4" />{{ saving ? "保存中…" : "保存并同步索引" }}
            </button>
          </div>
        </template>
        <div v-else class="mt-10 flex items-center justify-center text-secondarytext">
          <FileSearch class="mr-2 h-5 w-5" />请选择知识单元
        </div>
      </aside>
    </div>

    <div class="mt-4 flex items-center gap-2 text-xs text-secondarytext">
      <DatabaseZap class="h-4 w-4 text-brand" />
      正文变更采用 unit 级增量重建；title/category 仅同步 chunk 元数据，不重复 Embedding。
    </div>
  </div>
</template>

// frontend/src/pages/KnowledgeUnitsPage.tsx
import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Search, Trash2, ChevronLeft, ChevronRight, AlertTriangle } from "lucide-react";
import { PageHeader } from "@/components/shared/PageHeader";
import { PageLoading, ErrorState, EmptyState } from "@/components/shared/PageStates";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Card, CardContent } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { getKnowledgeUnits, batchDeleteUnits, type KnowledgeUnitItem } from "@/api/knowledge";
import { ApiError, type PageData } from "@/api/client";
import { formatDateTime } from "@/lib/utils";
import { usePermission } from "@/auth/AuthContext";

const STATUS_OPTIONS = [
  { value: "all", label: "全部状态" },
  { value: "active", label: "已生效" },
  { value: "vector_pending", label: "向量化待重试" },
  { value: "failed", label: "解析失败" },
] as const;

const PAGE_SIZE = 20;
const BATCH_DELETE_LIMIT = 100; // 接口约定文档 §7.3：ids 1–100（从严控制）

function StatusBadge({ status }: { status: KnowledgeUnitItem["status"] }) {
  const map = {
    active: { label: "已生效", cls: "bg-brand-soft text-ink" },
    vector_pending: { label: "向量化待重试", cls: "bg-review-soft text-ink" },
    failed: { label: "解析失败", cls: "bg-danger-soft text-danger" },
  } as const;
  const s = map[status];
  return <span className={`rounded-full px-2.5 py-0.5 text-xs font-semibold ${s.cls}`}>{s.label}</span>;
}

export default function KnowledgeUnitsPage() {
  const navigate = useNavigate();
  const can = usePermission();
  const canDelete = can("knowledge:delete");

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [data, setData] = useState<PageData<KnowledgeUnitItem> | null>(null);

  // 筛选状态（错误时保留用户输入，不清空）
  const [keyword, setKeyword] = useState("");
  const [status, setStatus] = useState<string>("all");
  const [page, setPage] = useState(1);

  const [selectedIds, setSelectedIds] = useState<number[]>([]);
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [deleteResult, setDeleteResult] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const resp = await getKnowledgeUnits({
        page,
        page_size: PAGE_SIZE,
        keyword: keyword || undefined,
        status: status === "all" ? undefined : status,
      });
      setData(resp);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "加载失败，请检查后端服务");
    } finally {
      setLoading(false);
    }
  }, [page, keyword, status]);

  useEffect(() => {
    void load();
  }, [load]);

  const totalPages = data ? Math.max(1, Math.ceil(data.total / data.page_size)) : 1;
  const allOnPageSelected =
    Boolean(data?.items.length) && data!.items.every((u) => selectedIds.includes(u.id));
  const overLimit = selectedIds.length > BATCH_DELETE_LIMIT;

  const toggleAll = () => {
    if (!data) return;
    setSelectedIds(
      allOnPageSelected ? [] : Array.from(new Set([...selectedIds, ...data.items.map((u) => u.id)])).slice(0, BATCH_DELETE_LIMIT),
    );
  };

  const toggleOne = (id: number) => {
    setSelectedIds((prev) => (prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]));
  };

  const handleDelete = async () => {
    setDeleting(true);
    setDeleteResult(null);
    try {
      const result = await batchDeleteUnits(selectedIds);
      if (result.failed?.length) {
        setDeleteResult(
          `部分失败：成功 ${result.succeeded.length} 条，失败 ${result.failed.length} 条（${result.failed
            .map((f) => `#${f.id} ${f.error_code}`)
            .join("、")}）`,
        );
      } else {
        setConfirmOpen(false);
        setSelectedIds([]);
        await load();
      }
    } catch (err) {
      setDeleteResult(err instanceof ApiError ? `删除失败：${err.message}` : "删除失败，请重试");
    } finally {
      setDeleting(false);
    }
  };

  return (
    <div className="animate-fade-up">
      <PageHeader
        title="知识单元"
        description="查找并维护具体知识单元：编号、标题、分类、格式、权限摘要与状态。"
      />

      {/* 筛选栏 */}
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center">
        <form
          className="relative flex-1 sm:max-w-xs"
          onSubmit={(e) => {
            e.preventDefault();
            setPage(1);
            void load();
          }}
        >
          <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-secondarytext" aria-hidden />
          <Input
            value={keyword}
            onChange={(e) => setKeyword(e.target.value)}
            placeholder="按标题关键字筛选"
            className="pl-9"
            aria-label="标题关键字"
          />
        </form>
        <Select
          value={status}
          onValueChange={(v) => {
            setStatus(v);
            setPage(1);
          }}
        >
          <SelectTrigger className="w-full sm:w-44" aria-label="状态筛选">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {STATUS_OPTIONS.map((o) => (
              <SelectItem key={o.value} value={o.value}>
                {o.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        {canDelete && selectedIds.length > 0 && (
          <Button
            variant="destructive"
            onClick={() => setConfirmOpen(true)}
            disabled={overLimit}
            className="shrink-0"
          >
            <Trash2 className="h-4 w-4" aria-hidden />
            批量删除（{selectedIds.length}）
          </Button>
        )}
      </div>

      {overLimit && (
        <p role="alert" className="mb-3 text-[13px] text-danger">
          单次批量删除最多 {BATCH_DELETE_LIMIT} 条，请缩减选择范围。
        </p>
      )}

      {loading && !data ? (
        <PageLoading />
      ) : error && !data ? (
        <ErrorState detail={error} onRetry={() => void load()} />
      ) : !data || data.items.length === 0 ? (
        <EmptyState
          title="暂无知识单元"
          description="可前往「知识导入」上传 PDF / Markdown / DOCX / TXT 文档，解析切片后生成知识单元。"
          action={
            <Button onClick={() => navigate("/knowledge/import")} disabled={!can("knowledge:write")}>
              前往知识导入
            </Button>
          }
        />
      ) : (
        <>
          {/* 桌面表格 */}
          <div className="hidden overflow-hidden rounded-lg border border-boundary bg-card md:block">
            <Table>
              <TableHeader>
                <TableRow className="bg-mist/70">
                  {canDelete && (
                    <TableHead className="w-10">
                      <Checkbox
                        checked={allOnPageSelected}
                        onCheckedChange={toggleAll}
                        aria-label="全选本页"
                      />
                    </TableHead>
                  )}
                  <TableHead>编号</TableHead>
                  <TableHead>标题</TableHead>
                  <TableHead>分类</TableHead>
                  <TableHead>格式</TableHead>
                  <TableHead>权限摘要</TableHead>
                  <TableHead>状态</TableHead>
                  <TableHead className="text-right">更新时间</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {data.items.map((u) => (
                  <TableRow key={u.id}>
                    {canDelete && (
                      <TableCell>
                        <Checkbox
                          checked={selectedIds.includes(u.id)}
                          onCheckedChange={() => toggleOne(u.id)}
                          aria-label={`选择 ${u.title}`}
                        />
                      </TableCell>
                    )}
                    <TableCell className="code-text text-secondarytext">{u.unit_code}</TableCell>
                    <TableCell className="max-w-[280px] truncate font-medium text-ink" title={u.title}>
                      {u.title}
                    </TableCell>
                    <TableCell className="text-secondarytext">{u.category ?? "—"}</TableCell>
                    <TableCell>
                      <span className="code-text rounded bg-mist px-1.5 py-0.5 text-xs text-secondarytext">
                        {u.file_type?.toUpperCase() ?? "—"}
                      </span>
                    </TableCell>
                    <TableCell className="max-w-[160px] truncate text-[13px] text-secondarytext" title={u.permissions_summary}>
                      {u.permissions_summary}
                    </TableCell>
                    <TableCell>
                      <StatusBadge status={u.status} />
                    </TableCell>
                    <TableCell className="text-right text-[13px] text-secondarytext">
                      {formatDateTime(u.updated_at)}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>

          {/* 移动端卡片列表（表格 → 实体卡片） */}
          <div className="space-y-3 md:hidden">
            {data.items.map((u) => (
              <Card key={u.id} className="border-boundary">
                <CardContent className="space-y-2 py-4">
                  <div className="flex items-start justify-between gap-3">
                    <p className="min-w-0 flex-1 font-medium text-ink">{u.title}</p>
                    <StatusBadge status={u.status} />
                  </div>
                  <p className="code-text text-xs text-secondarytext">{u.unit_code} · {u.category ?? "未分类"}</p>
                  <p className="truncate text-[13px] text-secondarytext">{u.permissions_summary}</p>
                  <p className="text-xs text-secondarytext/70">{formatDateTime(u.updated_at)}</p>
                </CardContent>
              </Card>
            ))}
          </div>

          {/* 分页 */}
          <div className="mt-4 flex items-center justify-between">
            <p className="text-[13px] text-secondarytext">
              共 {data.total} 条 · 第 {data.page}/{totalPages} 页
            </p>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" disabled={page <= 1 || loading} onClick={() => setPage((p) => p - 1)}>
                <ChevronLeft className="h-4 w-4" aria-hidden /> 上一页
              </Button>
              <Button
                variant="outline"
                size="sm"
                disabled={page >= totalPages || loading}
                onClick={() => setPage((p) => p + 1)}
              >
                下一页 <ChevronRight className="h-4 w-4" aria-hidden />
              </Button>
            </div>
          </div>
        </>
      )}

      {/* 批量删除二次确认（破坏性操作） */}
      <Dialog open={confirmOpen} onOpenChange={setConfirmOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-danger">
              <AlertTriangle className="h-5 w-5" aria-hidden /> 确认批量删除
            </DialogTitle>
            <DialogDescription>
              即将删除 <b>{selectedIds.length}</b> 个知识单元及其向量数据，操作不可恢复。
            </DialogDescription>
          </DialogHeader>
          {deleteResult && (
            <p role="alert" className="rounded-md bg-danger-soft px-3 py-2 text-[13px] text-danger">
              {deleteResult}
            </p>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setConfirmOpen(false)} disabled={deleting}>
              取消
            </Button>
            <Button variant="destructive" onClick={() => void handleDelete()} disabled={deleting}>
              {deleting ? "删除中…" : "确认删除"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
